### ISSUE TITLE
What is the default branch we are pushing pulling to?

### ISSUE THREAD

**Issue by nohe427** [Esri/developer-support#292]
Hey all!

I know we have been going back and forth between what branch is the default branch (gh-pages v. master) and I wanted to know what is the current one that will be the default or one that we PR to.

Can we put this in the readme?

Thanks! 👾

**Comment by nhaney90** [comment]
@nohe427  The default branch is now Master

**Comment by jgravois** [comment]
the default branch for any repository is the branch that is referenced when you visit its bare url.

![screenshot 2017-01-20 11 08 57](https://cloud.githubusercontent.com/assets/3011734/22161842/e538888c-df00-11e6-8f4b-6de30b0c34a8.png)

since the `gh-pages` branch is now gone completely, its impossible to make a new pull request to it.

i don't think the current state of the repository requires an explanation to new contributors, but if you or anyone else wants to propose some copy for the benefit of those that contributed previously via the `gh-pages` branch, please feel free.

**Comment by jgravois** [comment]
hah.  i can see now that someone with permission has pushed their own local `gh-pages` branch up.  i'll delete it (again).

all, please *do not* push work directly to **either** of the two branches below
* [Esri/developer-support/tree/gh-pages](https://github.com/Esri/developer-support/tree/gh-pages) 
* [Esri/developer-support/tree/master](https://github.com/Esri/developer-support/tree/master)  

make your commits in a named branch and open a pull request.
https://guides.github.com/introduction/flow/
